/*---------------------------------------------------------------------------------------------
 *  Copyright (c) FeimaCode. All rights reserved.
 *  Licensed under the MIT License.
 *
 *  Convenience shortcut: register the user's own Feima-hosted API access as
 *  plain `LocalEndpointRegistry` entries, so they join Auto's candidate pool
 *  through the existing, unmodified registration path (see candidateBuilder.ts,
 *  which builds Auto's pool exclusively from this registry).
 *
 *  This deliberately does NOT use VS Code's native BYOK mechanism
 *  (`lm.addLanguageModelsProviderGroup`) — that command creates an entry
 *  under VS Code's own vendor (e.g. "customendpoint"), a storage/vendor
 *  namespace `LocalEndpointRegistry`/`LocalEndpointProvider` cannot see. Since
 *  Auto's candidates come only from this registry, a native-BYOK entry could
 *  never be routed to by Auto — which defeats the point of this shortcut.
 *
 *  The template (base URL, completions path, and each model's curated
 *  metadata) is fetched from copilot-alternatives' public
 *  `byok-templates/feimacode.*` files at runtime (see byokTemplateSource.ts)
 *  rather than bundled here — a bundled copy would silently drift from that
 *  upstream reference (model roster, capabilities) with nothing to flag it.
 *  Only the URL/metadata shape is borrowed from it; registration itself goes
 *  through the same `upsertPersonalEntry`/`upsertModelOverride` calls any
 *  other local/enterprise endpoint uses.
 *
 *  Asks for a real static API key (`feima_sk_...`, generated by the user from
 *  the Feima dashboard — `keyUrl` on the template) rather than a snapshot of
 *  the live OAuth access token: OAuth tokens expire and need
 *  `FeimaAuthenticationService`'s refresh flow, which `LocalEndpointRegistry`'s
 *  secret storage (`context.secrets`) has no hook into. A static key is the
 *  credential that storage is actually built for.
 *
 *  No probe/validation before registering (unlike manual registration in
 *  manualRegistration.ts): the base URL and /models path are exactly what
 *  ModelCatalogService itself already calls successfully (see modelCatalog.ts),
 *  so re-validating here would be redundant.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { ILogService } from '../../../platform/log/common/logService';
import { getResolvedConfig } from '../../../../config/configService';
import { LocalEndpointRegistry } from '../localEndpointRegistry';
import { ByokGroup, fetchByokTemplate } from './byokTemplateSource';

export const FEIMA_HOSTED_SHORTCUT_COMMAND = 'feima.localModels.addFeimaHostedEndpoint';

/** Template name in copilot-alternatives' byok-templates/ catalog — see byokTemplateSource.ts. */
const TEMPLATE_NAME = 'feimacode';

/** Canonical host baked into the upstream template — rewritten per-install below for CN. */
const GLOBAL_API_BASE = 'https://api.feimacode.com/v1';

function completionsPathForApiType(apiType: string): string {
	switch (apiType) {
		case 'messages':
			return '/messages';
		case 'responses':
			return '/responses';
		case 'chat-completions':
		default:
			return '/chat/completions';
	}
}

function apiFormatForApiType(apiType: string): 'openai-compat' | 'anthropic-messages' {
	return apiType === 'messages' ? 'anthropic-messages' : 'openai-compat';
}

export function registerFeimaHostedShortcutCommand(
	context: vscode.ExtensionContext,
	registry: LocalEndpointRegistry,
	log: ILogService,
): vscode.Disposable {
	return vscode.commands.registerCommand(FEIMA_HOSTED_SHORTCUT_COMMAND, async () => {
		let template, groups;
		try {
			({ template, groups } = await vscode.window.withProgress(
				{ location: vscode.ProgressLocation.Notification, title: vscode.l10n.t('Fetching Feima model template...') },
				() => fetchByokTemplate(TEMPLATE_NAME, context, log),
			));
		} catch (error) {
			log.error(error as Error, '[feimaHostedShortcut] Failed to fetch model template');
			vscode.window.showErrorMessage(vscode.l10n.t('Could not fetch the Feima model template. Check your network connection and try again.'));
			return;
		}

		const apiKey = await vscode.window.showInputBox({
			title: template.displayName,
			prompt: template.keyInstructions,
			password: true,
			placeHolder: vscode.l10n.t('API key'),
			validateInput: value => value.trim() ? undefined : vscode.l10n.t('API key cannot be empty'),
		});
		if (!apiKey) {
			return;
		}

		// The fetched template's URLs point at the global endpoint (as
		// published upstream); rewrite the host for CN-region installs/settings
		// so the registered entry hits whatever endpoint this install actually
		// resolves to (see configService.ts).
		const apiBase = (getResolvedConfig().apiBaseUrl || GLOBAL_API_BASE).replace(/\/+$/, '');

		let registeredCount = 0;
		for (const group of groups) {
			registeredCount += await registerGroup(group, apiBase, apiKey, registry, log);
		}

		if (registeredCount > 0) {
			log.info(`[feimaHostedShortcut] Registered ${registeredCount} Feima-hosted model(s) across ${groups.length} group(s)`);
			vscode.window.showInformationMessage(
				vscode.l10n.t('Added your Feima-hosted models. They now appear in the model picker and can be routed to by Feima Auto.'),
			);
		} else {
			vscode.window.showErrorMessage(vscode.l10n.t('No Feima-hosted models were registered — see the log for details.'));
		}
	});
}

/**
 * Registers one template group as a single `LocalEndpointRegistry` entry
 * (connection recipe), plus a model override per listed model carrying the
 * template's curated metadata (`ModelOverride.manual: true` — see types.ts —
 * is exactly the "declare a model the endpoint's own /models listing doesn't
 * report" escape hatch, which lets the template's curated per-model
 * maxInputTokens/maxOutputTokens/toolCalling/vision win over whatever Feima's
 * own /models response happens to report). Returns the number of models
 * registered for this group.
 */
async function registerGroup(
	group: ByokGroup,
	apiBase: string,
	apiKey: string,
	registry: LocalEndpointRegistry,
	log: ILogService,
): Promise<number> {
	const entry = await registry.upsertPersonalEntry({
		baseEndpoint: apiBase,
		apiFormat: apiFormatForApiType(group.apiType),
		modelEndpointPath: '/models',
		completionsEndpointPath: completionsPathForApiType(group.apiType),
		origin: 'manual',
		label: vscode.l10n.t('Feima Hosted ({0})', group.name),
		apiKey,
	});

	let count = 0;
	for (const model of group.models) {
		const id = typeof model.id === 'string' ? model.id : undefined;
		if (!id) {
			log.warn(`[feimaHostedShortcut] Skipping a model in group "${group.name}" with no string "id" field`);
			continue;
		}
		await registry.upsertModelOverride({
			entryId: entry.id,
			modelId: id,
			name: typeof model.name === 'string' ? model.name : undefined,
			maxInputTokens: typeof model.maxInputTokens === 'number' ? model.maxInputTokens : undefined,
			maxOutputTokens: typeof model.maxOutputTokens === 'number' ? model.maxOutputTokens : undefined,
			toolCalling: typeof model.toolCalling === 'boolean' ? model.toolCalling : undefined,
			imageInput: typeof model.vision === 'boolean' ? model.vision : undefined,
			manual: true,
		});
		count++;
	}
	return count;
}
